contract:
  data: fift/data.fif
  func:
    - func/main.func
    - func/test/minter.func
    - func/test/wallet.func
  tests:
    - tests/test-admin.func
    - tests/test-get-method.func
    - tests/test-borrow.func
    - tests/test-lend.func
